#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling, testing and building your project before commiting'

npm run check-types ||
(
    echo 'Failed Type check.
             Are you seriously trying to write that? Make the changes required above.'
    false
)

npm run check-format ||
(
    echo 'Its F**ucking RAW --Your styling looks disgusting.
             Prettier Check Failed. Run npm run format, add changes and try commit again.'
    false
)

npm run check-lint ||
(
    echo 'Get the weak s**t out of here!.
             ESLint Check Failed. Make the required changes listed above, and changes and try to commit again'
    false
)

echo '...Alright... Code looks good to me... Trying to build now.'

npm run build ||
(
    echo 'Better call Bob... Because your build failed.
             Next build failed. View the errors above to see why.'
    false
)

echo 'You WIn this time... I am commiting this now.'